package com.cobra.seckillboot.dao;

import com.cobra.seckillboot.dataobject.ItemStockDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component("itemStockDOMapper")
public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jan 01 20:24:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jan 01 20:24:16 CST 2019
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jan 01 20:24:16 CST 2019
     */
    int insertSelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jan 01 20:24:16 CST 2019
     */
    ItemStockDO selectByPrimaryKey(Integer id);

    /**
     * 通过商品ID查库存
     */
    ItemStockDO selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jan 01 20:24:16 CST 2019
     */
    int updateByPrimaryKeySelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jan 01 20:24:16 CST 2019
     */
    int updateByPrimaryKey(ItemStockDO record);

    /**
     * 减库存
     * @param itemId
     * @param amount
     * @return
     */
    int decreaseStock(@Param("itemId")Integer itemId, @Param("amount")Integer amount);

}