package com.cobra.seckillboot.dao;

import com.cobra.seckillboot.dataobject.PromoDO;
import org.springframework.stereotype.Component;

@Component("promoDOMapper")
public interface PromoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 02 20:13:30 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 02 20:13:30 CST 2019
     */
    int insert(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 02 20:13:30 CST 2019
     */
    int insertSelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 02 20:13:30 CST 2019
     */
    PromoDO selectByPrimaryKey(Integer id);

    /**
     * 通过itemid获取promdo
     */
    PromoDO selectByItemId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 02 20:13:30 CST 2019
     */
    int updateByPrimaryKeySelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Wed Jan 02 20:13:30 CST 2019
     */
    int updateByPrimaryKey(PromoDO record);
}