package com.cobra.seckillboot.dao;

import com.cobra.seckillboot.dataobject.UserDO;
import org.springframework.stereotype.Component;

@Component(value = "userDOMapper") //可以不加，但是用@Autowired时，对象下会有下划红线报错，使用@Resoure就没有
public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Dec 27 23:46:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Dec 27 23:46:51 CST 2018
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Dec 27 23:46:51 CST 2018
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Dec 27 23:46:51 CST 2018
     */
    UserDO selectByPrimaryKey(Integer id);

    /**
     * 通过手机号查询用户
     * @param telphone
     * @return
     */
    UserDO selectByTelphone(String telphone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Dec 27 23:46:51 CST 2018
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Dec 27 23:46:51 CST 2018
     */
    int updateByPrimaryKey(UserDO record);
}